### ISSUE TITLE
Conflicts with python thrift library

### ISSUE THREAD

**Issue by pjz** [evernote/evernote-sdk-python#33] opened 2014-09-29 17:47 UTC
doing `pip install evernote` and `pip install thrift` can cause:

```
File "/usr/local/lib/python2.7/site-packages/notehandler-0.6_dev-py2.7.egg/notehandler.py", line 315, in cmd_userinfo
userStore = client.get_user_store()
File "/usr/local/lib/python2.7/site-packages/evernote-1.25.0-py2.7.egg/evernote/api/client.py", line 60, in get_user_store
store = Store(self.token, UserStore.Client, user_store_uri)
File "/usr/local/lib/python2.7/site-packages/evernote-1.25.0-py2.7.egg/evernote/api/client.py", line 122, in init
self._client = self._get_thrift_client(client_class, store_url)
File "/usr/local/lib/python2.7/site-packages/evernote-1.25.0-py2.7.egg/evernote/api/client.py", line 146, in _get_thrift_client
http_client.addHeaders({
AttributeError: THttpClient instance has no attribute 'addHeaders'
```

Can you guys work with the thrift library to fix this?  Or unbundle the thrift library?  Or pull it all the way internal so you don't collide namespacewise so this won't happen?

**Comment by pjz** [comment] 2015-01-22 17:14
Did that repro work for you?

**Comment by matthewayne** [comment] 2015-05-29 00:30
We have reproduced the issue and a fix is in the works for the next version.

**Comment by dg2** [comment] 2015-11-01 01:59
The standard Thrift's THttpClient support custom headers through setCustomHeaders, so it would be better to use that instead of rolling out your own version of Thrift (unless there are more changes ...)

**Comment by pjz** [comment] 2015-11-01 20:14
6 months to repro. 5 months of 'working on a fix'... I'm glad they're working on it, but I'm way past holding my breath.

**Comment by dg2** [comment] 2015-11-01 20:31
Makes sense :) In case you need a fix, you can just change the function `_get_thrift_client` in `lib/evernote/api/client.py` to use
```
    http_client.setCustomHeaders({
            'User-Agent': "%s / %s; Python / %s;"
            % (self._user_agent_id, self._get_sdk_version(), sys.version.replace('\n', ""))
        })
```
instead of using `http_client.addHeaders`. Then remove the thrift folder in `lib` and in principle you're good to go (works for me ®)

**Comment by pjz** [comment] 2015-11-04 01:56
Yah, I don't use thrift myself, I just use the evernote package to power my notehandler app.  A user reported this as an issue to notehandler (see above).  It really does look to be evernote's issue; they should either 1) unbundle thrift and depend on some version of it (preferred, IMO) or 2) bundle some particular version but rename it to something like `evernote.thrift` so they don't collide with the main `thrift` package.

**Closed** 2018-03-28 01:19 UTC
